In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
store_access = pd.read_csv('store_access.csv')
store_access

,fips,state,county,pop_low_access_15,percent_pop_low_access_15,low_income_low_access_15,percent_low_income_low_access_15,no_car_low_access_15,percent_no_car_low_access_15,snap_low_access_15,...,hispanic_low_access_15,percent_hispanic_low_access_15,asian_low_access_15,percent_asian_low_access_15,nhna_low_access_15,percent_nhna_low_access_15,nhpi_low_access_15,percent_nhpi_low_access_15,multiracial_low_access_15,percent_multiracial_low_access_15
0,1001,AL,Autauga,17496.693040,0.32,6543.676824,0.12,677.672769,0.03,931.935186,...,471.136164,0.01,86.767975,0.0,61.169869,0.0,8.817961,0.0,482.848633,0.01
1,1003,AL,Baldwin,30561.264430,0.17,9886.831137,0.05,1394.162766,0.02,950.535290,...,1377.874834,0.01,212.946378,0.0,181.649648,0.0,14.819634,0.0,1127.696098,0.01
2,1005,AL,Barbour,6069.523628,0.22,2948.790251,0.11,425.144927,0.04,422.569040,...,509.377525,0.02,17.096410,0.0,39.960527,0.0,8.082376,0.0,462.382655,0.02
3,1007,AL,Bibb,969.378841,0.04,596.162829,0.03,224.388125,0.03,53.818772,...,8.596762,0.00,1.994318,0.0,2.513097,0.0,0.000000,0.0,5.259244,0.00
4,1009,AL,Blount,3724.428242,0.06,1650.959482,0.03,719.931444,0.03,175.370338,...,497.489891,0.01,8.428994,0.0,28.938242,0.0,1.062851,0.0,202.914186,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3138,56037,WY,Sweetwater,18934.737810,0.43,4750.905615,0.11,359.608360,0.02,352.866113,...,2661.350520,0.06,114.722086,0.0,189.621441,0.0,27.720443,0.0,1605.391465,0.04
3139,56039,WY,Teton,6212.390430,0.29,1577.771012,0.07,48.474161,0.01,60.192270,...,736.174507,0.03,53.489780,0.0,32.482255,0.0,8.468847,0.0,460.434464,0.02
3140,56041,WY,Uinta,4686.017653,0.22,2054.179828,0.10,211.630840,0.03,158.918171,...,535.616715,0.03,13.831709,0.0,40.339658,0.0,6.586104,0.0,350.320469,0.02
3141,56043,WY,Washakie,931.411647,0.11,309.030331,0.04,42.030853,0.01,36.804973,...,35.474502,0.00,6.366775,0.0,5.006976,0.0,0.000000,0.0,34.160542,0.00
3142,56045,WY,Weston,1237.267037,0.17,302.697580,0.04,112.645982,0.04,29.336258,...,28.073114,0.00,2.771750,0.0,10.372147,0.0,0.507750,0.0,24.811192,0.00

In [3]:
#checking data types
store_access.dtypes

fips                                   int64
state                                 object
county                                object
pop_low_access_15                    float64
percent_pop_low_access_15            float64
low_income_low_access_15             float64
percent_low_income_low_access_15     float64
no_car_low_access_15                 float64
percent_no_car_low_access_15         float64
snap_low_access_15                   float64
percent_snap_low_access_15           float64
child_low_access_15                  float64
percent_child_low_access_15          float64
senior_low_access_15                 float64
percent_senior_low_access_15         float64
white_low_access_15                  float64
percent_white_low_access_15          float64
black_low_access_15                  float64
percent_black_low_access_15          float64
hispanic_low_access_15               float64
percent_hispanic_low_access_15       float64
asian_low_access_15                  float64
percent_asian_low_access_15          float64
nhna_low_access_15                   float64
percent_nhna_low_access_15           float64
nhpi_low_access_15                   float64
percent_nhpi_low_access_15           float64
multiracial_low_access_15            float64
percent_multiracial_low_access_15    float64
dtype: object

In [4]:
#copy in case I want to do any testing later
store_access_copy = store_access.copy()

In [5]:
#changing fips to category
store_access['fips'] = store_access['fips'].astype('category')

In [6]:
store_access.describe()

,pop_low_access_15,percent_pop_low_access_15,low_income_low_access_15,percent_low_income_low_access_15,no_car_low_access_15,percent_no_car_low_access_15,snap_low_access_15,percent_snap_low_access_15,child_low_access_15,percent_child_low_access_15,...,hispanic_low_access_15,percent_hispanic_low_access_15,asian_low_access_15,percent_asian_low_access_15,nhna_low_access_15,percent_nhna_low_access_15,nhpi_low_access_15,percent_nhpi_low_access_15,multiracial_low_access_15,percent_multiracial_low_access_15
count,3124.000000,3124.000000,3123.000000,3123.000000,3140.000000,3140.000000,3123.000000,3123.000000,3124.000000,3124.000000,...,3124.000000,3124.000000,3124.000000,3124.000000,3124.000000,3124.000000,3124.000000,3124.000000,3124.000000,3124.000000
mean,19287.747386,0.230851,5833.959524,0.086449,673.746375,0.032777,804.471927,0.029116,4742.980900,0.053992,...,2326.081648,0.019731,695.064178,0.001719,230.259498,0.007308,32.204247,0.000061,1290.799156,0.011034
std,47803.525595,0.196054,13989.348252,0.083807,1100.580817,0.032298,1870.844498,0.031776,12216.611681,0.048233,...,12159.928409,0.050606,3466.438554,0.007230,1387.887687,0.048444,435.841952,0.001301,5414.425184,0.019070
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1631.358726,0.110000,608.235919,0.040000,126.004765,0.020000,68.476725,0.010000,354.654348,0.020000,...,31.131894,0.000000,3.328667,0.000000,5.274117,0.000000,0.000000,0.000000,33.382261,0.000000
50%,4131.174278,0.190000,1636.858816,0.070000,340.348323,0.030000,218.176102,0.020000,956.123349,0.040000,...,136.051404,0.010000,16.473665,0.000000,20.850829,0.000000,1.000000,0.000000,132.098182,0.010000
75%,13119.029393,0.290000,4859.016156,0.110000,755.806483,0.040000,687.003195,0.040000,3020.174780,0.070000,...,874.891533,0.020000,130.916653,0.000000,101.353615,0.000000,7.107201,0.000000,658.924526,0.010000
max,740267.412700,1.000000,259479.516000,0.720000,13845.220200,0.610000,29461.297950,0.370000,219002.492900,0.390000,...,263440.500100,0.790000,76998.348560,0.250000,40350.800430,0.840000,21387.063060,0.040000,115781.021500,0.270000

In [7]:
store_access.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3143 entries, 0 to 3142
Data columns (total 29 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   fips                               3143 non-null   category
 1   state                              3143 non-null   object
 2   county                             3143 non-null   object
 3   pop_low_access_15                  3124 non-null   float64
 4   percent_pop_low_access_15          3124 non-null   float64
 5   low_income_low_access_15           3123 non-null   float64
 6   percent_low_income_low_access_15   3123 non-null   float64
 7   no_car_low_access_15               3140 non-null   float64
 8   percent_no_car_low_access_15       3140 non-null   float64
 9   snap_low_access_15                 3123 non-null   float64
 10  percent_snap_low_access_15         3123 non-null   float64
 11  child_low_access_15                3124 non-null   float64
 12  percent_child_low_access_15        3124 non-null   float64
 13  senior_low_access_15               3124 non-null   float64
 14  percent_senior_low_access_15       3124 non-null   float64
 15  white_low_access_15                3124 non-null   float64
 16  percent_white_low_access_15        3124 non-null   float64
 17  black_low_access_15                3124 non-null   float64
 18  percent_black_low_access_15        3124 non-null   float64
 19  hispanic_low_access_15             3124 non-null   float64
 20  percent_hispanic_low_access_15     3124 non-null   float64
 21  asian_low_access_15                3124 non-null   float64
 22  percent_asian_low_access_15        3124 non-null   float64
 23  nhna_low_access_15                 3124 non-null   float64
 24  percent_nhna_low_access_15         3124 non-null   float64
 25  nhpi_low_access_15                 3124 non-null   float64
 26  percent_nhpi_low_access_15         3124 non-null   float64
 27  multiracial_low_access_15          3124 non-null   float64
 28  percent_multiracial_low_access_15  3124 non-null   float64
dtypes: category(1), float64(26), object(2)
memory usage: 782.9+ KB

In [8]:
states = {
        'AK': 'O',
        'AL': 'S',
        'AR': 'S',
        'AS': 'O',
        'AZ': 'W',
        'CA': 'W',
        'CO': 'W',
        'CT': 'N',
        'DC': 'N',
        'DE': 'N',
        'FL': 'S',
        'GA': 'S',
        'GU': 'O',
        'HI': 'O',
        'IA': 'M',
        'ID': 'W',
        'IL': 'M',
        'IN': 'M',
        'KS': 'M',
        'KY': 'S',
        'LA': 'S',
        'MA': 'N',
        'MD': 'N',
        'ME': 'N',
        'MI': 'W',
        'MN': 'M',
        'MO': 'M',
        'MP': 'O',
        'MS': 'S',
        'MT': 'W',
        'NA': 'O',
        'NC': 'S',
        'ND': 'M',
        'NE': 'W',
        'NH': 'N',
        'NJ': 'N',
        'NM': 'W',
        'NV': 'W',
        'NY': 'N',
        'OH': 'M',
        'OK': 'S',
        'OR': 'W',
        'PA': 'N',
        'PR': 'O',
        'RI': 'N',
        'SC': 'S',
        'SD': 'M',
        'TN': 'S',
        'TX': 'S',
        'UT': 'W',
        'VA': 'S',
        'VI': 'O',
        'VT': 'N',
        'WA': 'W',
        'WI': 'M',
        'WV': 'S',
        'WY': 'W'
}

In [9]:
#looking for NaN and -9999

res2 = store_access.isin(['-9999','', 'NaN', '-']).any().any()
  
if res2:
    print("\nany of the mention value exists in Dataframe")
      
else:
    print("\nNone of thses values exists in Dataframe")

None of thses values exists in Dataframe

In [11]:
# Checking for NaN values

store_access.isnull().values.any()
store_access.isnull().sum().sum()

466

In [12]:
store_access.to_csv("store_access_clean.csv")